# Generated by Django 5.0 on 2023-12-25 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concierge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_name', models.CharField(max_length=200, verbose_name='Name and lastname')),
                ('document', models.CharField(max_length=11, verbose_name='Concierge document (CPF)')),
                ('phone', models.CharField(max_length=11, verbose_name='Concierge phone')),
                ('birthdate', models.DateField(verbose_name='Concierge birthdate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Concierge',
                'verbose_name_plural': 'Concierges',
                'db_table': 'concierge',
            },
        ),
    ]
